#!/bin/bash
exec scala "$0" "$@"
!#

import scala.sys.process._

// Create tags, e.g. `git tag step-01 fa9f74c`
(Process("git log --oneline").lines.reverse drop 2).zipWithIndex foreach {
  case (s, n) => Process(f"git tag -f step-$n%02d ${s take 7}").!
}

// Push tags to remote repo
"git push --tags -f".!
